title: Àngel Ollé Blázquez
description: Specialist Solution Architect @ Red Hat
title-override: Àngel Ollé Blázquez | Specialist Solution Architect
remote_theme: pages-themes/slate@v0.2.0
show_downloads: false
plugins:
- jekyll-remote-theme
