title: Àngel Ollé Blázquez
description: Specialist Solution Architect @ Red Hat  [![Linkedin](/assets/images/linkedin.png)](https://www.linkedin.com/in/angelolle/){:target="_blank" rel="noopener noreferrer"}
title-override: Àngel Ollé Blázquez | Specialist Solution Architect
remote_theme: pages-themes/slate@v0.2.0
show_downloads: false
plugins:
- jekyll-remote-theme
